framework:
  messenger:
    transports:
      amqp:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        options:
          exchange:
            name: 'product_exchange'
            type: topic
          queues:
            shopify_product_queue:
              binding_keys: [ 'shopify_product' ]

    routing:
      'App\Domain\Message\ProductMessage': amqp

